// lib/shared/firebase_service.dart
// Handles: Firebase init, Auth (child/parent), Firestore CRUD, FCM messaging
//
// Firestore Rules (paste in Firebase Console > Firestore > Rules):
// rules_version = '2';
// service cloud.firestore {
//   match /databases/{database}/documents {
//     // Function to check if user is super admin
//     function isSuperAdmin() {
//       return get(/databases/$(database)/documents/users/$(request.auth.uid)).data.role == "super_admin";
//     }
//     match /devices/{deviceId} {
//       allow read: if request.auth != null;
//       allow write: if request.auth != null &&
//         (isSuperAdmin() ||
//          request.auth.uid == resource.data.parentUid ||
//          request.auth.uid == resource.data.childUid);
//     }
//     match /users/{userId} {
//       allow read, write: if request.auth.uid == userId || isSuperAdmin();
//     }
//   }
// }

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import '../firebase_options.dart'; // Generated by: flutterfire configure
import 'models/user_model.dart';
import 'models/device_model.dart';

/// Top-level FCM background handler (must be top-level function)
@pragma('vm:entry-point')
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  debugPrint('//TEST: Background FCM received: ${message.data}');
}

class FirebaseService {
  static FirebaseService? _instance;
  static FirebaseService get instance => _instance ??= FirebaseService._();
  FirebaseService._();

  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FirebaseFirestore _db = FirebaseFirestore.instance;
  final FirebaseMessaging _fcm = FirebaseMessaging.instance;

  User? get currentUser => _auth.currentUser;
  String? get currentUid => _auth.currentUser?.uid;
  Stream<User?> get authStateChanges => _auth.authStateChanges();

  // ─── Firebase Init ───────────────────────────────────────────────────────

  static Future<void> initFirebase() async {
    try {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform, // from flutterfire configure
      );
      FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
      debugPrint('//TEST: Firebase initialized OK');
    } catch (e) {
      debugPrint('//TEST: Firebase init error: $e');
      rethrow;
    }
  }

  // ─── Auth ────────────────────────────────────────────────────────────────

  /// Sign up with email/password and store role in Firestore
  Future<UserCredential?> signUp({
    required String email,
    required String password,
    required String role, // 'parent' or 'child'
  }) async {
    try {
      final cred = await _auth.createUserWithEmailAndPassword(
        email: email,
        password: password,
      );
      // Store user role
      await _db.collection('users').doc(cred.user!.uid).set({
        'email': email,
        'role': role,
        'createdAt': FieldValue.serverTimestamp(),
      });
      debugPrint('//TEST: SignUp OK uid=${cred.user!.uid} role=$role');
      return cred;
    } on FirebaseAuthException catch (e) {
      debugPrint('//TEST: SignUp error: ${e.code} - ${e.message}');
      rethrow;
    } catch (e) {
      debugPrint('//TEST: SignUp unexpected error: $e');
      rethrow;
    }
  }

  /// Sign in with email/password
  Future<UserCredential?> signIn({
    required String email,
    required String password,
  }) async {
    try {
      final cred = await _auth.signInWithEmailAndPassword(
        email: email,
        password: password,
      );
      debugPrint('//TEST: SignIn OK uid=${cred.user!.uid}');

      // Ensure user document exists (upsert)
      final uid = cred.user!.uid;
      final doc = await _db.collection('users').doc(uid).get();
      if (!doc.exists) {
        await _db.collection('users').doc(uid).set({
          'email': email,
          'role': 'parent',
          'plan': 'trial',
          'createdAt': FieldValue.serverTimestamp(),
        });
        debugPrint('//TEST: Created missing user doc for $uid');
      }

      return cred;
    } on FirebaseAuthException catch (e) {
      debugPrint('//TEST: SignIn error: ${e.code} - ${e.message}');
      rethrow;
    }
  }

  /// Sign in with Google (Web specific Popup)
  Future<UserCredential?> signInWithGoogle() async {
    try {
      final googleProvider = GoogleAuthProvider();
      googleProvider.addScope('email');
      
      final cred = await _auth.signInWithPopup(googleProvider);
      debugPrint('//TEST: Google SignIn OK uid=${cred.user!.uid}');

      // Ensure user document exists (auto free account)
      final uid = cred.user!.uid;
      final doc = await _db.collection('users').doc(uid).get();
      if (!doc.exists) {
        await _db.collection('users').doc(uid).set({
          'email': cred.user?.email ?? '',
          'displayName': cred.user?.displayName ?? '',
          'photoUrl': cred.user?.photoURL ?? '',
          'role': 'parent',
          'plan': 'trial', // Default free account
          'createdAt': FieldValue.serverTimestamp(),
        });
        debugPrint('//TEST: Created missing user doc for $uid via Google');
      }

      return cred;
    } on FirebaseAuthException catch (e) {
      debugPrint('//TEST: Google SignIn error: ${e.code} - ${e.message}');
      rethrow;
    } catch (e) {
      debugPrint('//TEST: Google SignIn general error: $e');
      rethrow;
    }
  }

  /// Sign in with Facebook (Simulated for Web demo)
  Future<UserCredential?> signInWithFacebook() async {
    try {
      final facebookProvider = FacebookAuthProvider();
      facebookProvider.addScope('email');
      
      final cred = await _auth.signInWithPopup(facebookProvider);
      debugPrint('//TEST: Facebook SignIn OK uid=${cred.user!.uid}');

      // Ensure user document exists
      final uid = cred.user!.uid;
      final doc = await _db.collection('users').doc(uid).get();
      if (!doc.exists) {
        await _db.collection('users').doc(uid).set({
          'email': cred.user?.email ?? '',
          'displayName': cred.user?.displayName ?? '',
          'role': 'parent',
          'plan': 'trial',
          'createdAt': FieldValue.serverTimestamp(),
        });
      }

      return cred;
    } on FirebaseAuthException catch (e) {
      debugPrint('//TEST: Facebook SignIn error: ${e.code} - ${e.message}');
      rethrow;
    }
  }

  Future<void> signOut() async {
    try {
      await _auth.signOut();
      debugPrint('//TEST: SignOut OK');
    } catch (e) {
      debugPrint('//TEST: SignOut error: $e');
    }
  }

  /// Stream current user data
  Stream<UserModel?> streamCurrentUser() {
    final uid = currentUid;
    if (uid == null) return Stream.value(null);
    final docRef = _db.collection('users').doc(uid);
    
    // Ensure user doc exists (handles persisted auth sessions)
    _ensureUserDoc(uid);
    
    return docRef.snapshots().map((doc) {
      if (!doc.exists) return null;
      return UserModel.fromDoc(doc);
    });
  }

  /// Create user doc if missing (idempotent)
  Future<void> _ensureUserDoc(String uid) async {
    try {
      final doc = await _db.collection('users').doc(uid).get();
      if (!doc.exists) {
        await _db.collection('users').doc(uid).set({
          'email': _auth.currentUser?.email ?? '',
          'role': 'parent',
          'plan': 'trial',
          'createdAt': FieldValue.serverTimestamp(),
        });
        debugPrint('//TEST: Auto-created missing user doc for $uid');
      }
    } catch (e) {
      debugPrint('//TEST: _ensureUserDoc error: $e');
    }
  }

  /// Update user plan (SaaS Simulation)
  Future<void> updateUserPlan(String planType) async {
    if (currentUid == null) return;
    final now = DateTime.now();
    DateTime expiry;
    if (planType == 'trial') {
      expiry = now.add(const Duration(days: 7));
    } else {
      expiry = now.add(const Duration(days: 365)); // 1 year for paid
    }

    await _db.collection('users').doc(currentUid).update({
      'plan': planType,
      'expiryDate': Timestamp.fromDate(expiry),
    });
  }

  Future<Map<String, dynamic>?> getUserData(String uid) async {
    try {
      final doc = await _db.collection('users').doc(uid).get();
      return doc.data();
    } catch (e) {
      debugPrint('//TEST: getUserData error: $e');
      return null;
    }
  }

  // ─── Firestore: Device ───────────────────────────────────────────────────

  /// Register or update device record
  /// Path: /devices/{deviceId}
  Future<void> registerDevice({
    required String deviceId,
    required String childUid,
    required String parentUid,
    String? model,
  }) async {
    try {
      await _db.collection('devices').doc(deviceId).set({
        'deviceId': deviceId,
        'childUid': childUid,
        'parentUid': parentUid,
        'model': model ?? 'Unknown',
        'locked': false,
        'pin': '1234',
        'status': 'online',
        'lat': 0.0,
        'lng': 0.0,
        'battery': 0,
        'lastSeen': FieldValue.serverTimestamp(),
        'fcmToken': '',
        'hiddenApps': [],
        'blockedApps': [],
        'controlMode': 'basic',
        'tempAccess': {},
        'warningList': [],
        'warningTitle': 'Restricted Access',
        'taskList': [],
        'taskTitle': 'Parent Tasks',
      }, SetOptions(merge: true));
      debugPrint('//TEST: Device registered: $deviceId');
    } catch (e) {
      debugPrint('//TEST: registerDevice error: $e');
      rethrow;
    }
  }

  /// Parent Dashboard: Create a temporary pairing session with a 6-digit code
  Future<void> createPairingSession(String parentUid, String code) async {
    try {
      await _db.collection('pairing_sessions').doc(code).set({
        'parentUid': parentUid,
        'createdAt': FieldValue.serverTimestamp(),
        'expiresAt': Timestamp.fromDate(DateTime.now().add(const Duration(minutes: 30))),
      });
      debugPrint('//TEST: Created pairing session for code $code');
    } catch (e) {
      debugPrint('//TEST: createPairingSession error: $e');
    }
  }

  /// Child App: Link to parent using a 6-digit code
  Future<String?> getParentUidByCode(String code) async {
    try {
      debugPrint('//TEST: Querying pairing_sessions for code: $code');
      final doc = await _db.collection('pairing_sessions').doc(code).get();
      if (!doc.exists) {
        debugPrint('//TEST: Pairing session NOT FOUND for code: $code');
        return null;
      }
      
      final data = doc.data()!;
      final expiresAt = data['expiresAt'] as Timestamp?;
      if (expiresAt != null && expiresAt.toDate().isBefore(DateTime.now())) {
        debugPrint('//TEST: Pairing session EXPIRED for code: $code');
        await doc.reference.delete();
        return null;
      }
      
      final parentUid = data['parentUid'] as String;
      debugPrint('//TEST: Pairing session VALID for code: $code (Parent: $parentUid)');
      
      // Delete after use
      await doc.reference.delete();
      return parentUid;
    } catch (e) {
      debugPrint('//TEST: getParentUidByCode error: $e');
      return null;
    }
  }


  /// Update device location + battery + status
  Future<void> updateDeviceData({
    required String deviceId,
    double? lat,
    double? lng,
    int? battery,
    String? status,
    bool? locked,
  }) async {
    try {
      final Map<String, dynamic> data = {
        'lastSeen': FieldValue.serverTimestamp(),
      };
      if (lat != null) data['lat'] = lat;
      if (lng != null) data['lng'] = lng;
      if (battery != null) data['battery'] = battery;
      if (status != null) data['status'] = status;
      if (locked != null) data['locked'] = locked;

      await _db.collection('devices').doc(deviceId).update(data);
      debugPrint('//TEST: Device data updated: $deviceId lat=$lat battery=$battery locked=$locked');
    } catch (e) {
      debugPrint('//TEST: updateDeviceData error: $e');
      // Don't rethrow — background service should not crash
    }
  }

  /// Get device locked state (for 30s heartbeat poll)
  Future<bool> getDeviceLocked(String deviceId) async {
    try {
      final doc = await _db.collection('devices').doc(deviceId).get();
      final locked = doc.data()?['locked'] as bool? ?? false;
      debugPrint('//TEST: getDeviceLocked: $deviceId = $locked');
      return locked;
    } catch (e) {
      debugPrint('//TEST: getDeviceLocked error: $e');
      return false; // Default: unlocked (safe)
    }
  }

  /// Stream device document (real-time)
  Stream<DocumentSnapshot<Map<String, dynamic>>> streamDevice(String deviceId) {
    return _db.collection('devices').doc(deviceId).snapshots();
  }

  /// Stream all devices for a parent
  Stream<QuerySnapshot<Map<String, dynamic>>> streamParentDevices(
      String parentUid) {
    return _db
        .collection('devices')
        .where('parentUid', isEqualTo: parentUid)
        .snapshots();
  }

  /// Stream devices based on admin role
  Stream<QuerySnapshot<Map<String, dynamic>>> streamAdminDevices() {
    final uid = _auth.currentUser?.uid;
    if (uid == null) return const Stream.empty();
    
    return _db.collection('users').doc(uid).snapshots().asyncExpand((userDoc) {
      if (!userDoc.exists) {
        return _db.collection('devices').where('parentUid', isEqualTo: uid).snapshots();
      }
      final role = userDoc.data()?['role'] ?? 'parent';
      if (role == 'super_admin') {
        return _db.collection('devices').snapshots();
      } else {
        return _db.collection('devices').where('parentUid', isEqualTo: uid).snapshots();
      }
    });
  }

  /// Parent: set locked state for a device
  Future<void> setDeviceLocked(String deviceId, bool locked) async {
    try {
      await _db.collection('devices').doc(deviceId).update({'locked': locked});
      debugPrint('//TEST: setDeviceLocked: $deviceId locked=$locked');
    } catch (e) {
      debugPrint('//TEST: setDeviceLocked error: $e');
      rethrow;
    }
  }

  /// Parent: set custom PIN for a device
  Future<void> updateDevicePin(String deviceId, String pin) async {
    try {
      await _db.collection('devices').doc(deviceId).update({'pin': pin});
      debugPrint('//TEST: updateDevicePin: $deviceId pin updated');
    } catch (e) {
      debugPrint('//TEST: updateDevicePin error: $e');
      rethrow;
    }
  }

  /// Parent: update Task List for a device (Locked Screen)
  Future<void> updateDeviceTaskList(String deviceId, List<String> taskList) async {
    try {
      await _db.collection('devices').doc(deviceId).update({'taskList': taskList});
      debugPrint('//TEST: updateDeviceTaskList: $deviceId tasks updated');
    } catch (e) {
      debugPrint('//TEST: updateDeviceTaskList error: $e');
      rethrow;
    }
  }

  /// Parent: update Task Title for a device (Locked Screen)
  Future<void> updateDeviceTaskTitle(String deviceId, String title) async {
    try {
      await _db.collection('devices').doc(deviceId).update({'taskTitle': title});
      debugPrint('//TEST: updateDeviceTaskTitle: $deviceId title updated to $title');
    } catch (e) {
      debugPrint('//TEST: updateDeviceTaskTitle error: $e');
      rethrow;
    }
  }

  /// Parent: update Warning List for a device (Smart Blocker)
  Future<void> updateDeviceWarningList(String deviceId, List<String> warningList) async {
    try {
      await _db.collection('devices').doc(deviceId).update({'warningList': warningList});
      debugPrint('//TEST: updateDeviceWarningList: $deviceId warnings updated');
    } catch (e) {
      debugPrint('//TEST: updateDeviceWarningList error: $e');
      rethrow;
    }
  }

  /// Parent: update Warning Title for a device (Smart Blocker)
  Future<void> updateDeviceWarningTitle(String deviceId, String title) async {
    try {
      await _db.collection('devices').doc(deviceId).update({'warningTitle': title});
      debugPrint('//TEST: updateDeviceWarningTitle: $deviceId title updated to $title');
    } catch (e) {
      debugPrint('//TEST: updateDeviceWarningTitle error: $e');
      rethrow;
    }
  }

  /// Parent: update Hidden Apps list for a device
  Future<void> updateDeviceHiddenApps(String deviceId, List<String> hiddenApps) async {
    try {
      await _db.collection('devices').doc(deviceId).update({'hiddenApps': hiddenApps});
      debugPrint('//TEST: updateDeviceHiddenApps: $deviceId hiddenApps updated');
    } catch (e) {
      debugPrint('//TEST: updateDeviceHiddenApps error: $e');
      rethrow;
    }
  }

  /// Parent: update Blocked Apps list for a device (for basic mode)
  Future<void> updateDeviceBlockedApps(String deviceId, List<String> blockedApps) async {
    try {
      await _db.collection('devices').doc(deviceId).update({'blockedApps': blockedApps});
      debugPrint('//TEST: updateDeviceBlockedApps: $deviceId blockedApps updated');
    } catch (e) {
      debugPrint('//TEST: updateDeviceBlockedApps error: $e');
      rethrow;
    }
  }

  /// Parent: update Control Mode (Basic vs Advanced)
  Future<void> updateControlMode(String deviceId, String mode) async {
    try {
      await _db.collection('devices').doc(deviceId).update({'controlMode': mode});
    } catch (e) {
      debugPrint('//TEST: updateControlMode error: $e');
      rethrow;
    }
  }

  /// Parent: update Temp Access for an app
  /// FIX: Store as epoch milliseconds (not Firestore Timestamp) so native Kotlin can read directly
  Future<void> updateTempAccess(String deviceId, String packageName, int minutes) async {
    try {
      final expiry = DateTime.now().add(Duration(minutes: minutes));
      await _db.collection('devices').doc(deviceId).set({
        'tempAccess': {
          packageName: expiry.millisecondsSinceEpoch,
        }
      }, SetOptions(merge: true));
    } catch (e) {
      debugPrint('//TEST: updateTempAccess error: $e');
      rethrow;
    }
  }

  /// Child: push installed apps to Firestore
  /// Uses set(merge) so writes succeed even if the doc was created with non-standard fields;
  /// keeps payload small (no per-app icon blobs) to stay under the 1 MiB document limit.
  Future<void> updateInstalledApps(String deviceId, List<Map<String, dynamic>> apps) async {
    try {
      await _db.collection('devices').doc(deviceId).set(
            {'installedApps': apps},
            SetOptions(merge: true),
          );
      debugPrint('//TEST: updateInstalledApps OK: $deviceId count=${apps.length}');
    } on FirebaseException catch (e) {
      debugPrint(
        '//TEST: updateInstalledApps FirebaseException code=${e.code} message=${e.message}',
      );
      rethrow;
    } catch (e) {
      debugPrint('//TEST: updateInstalledApps error: $e');
      rethrow;
    }
  }

  /// Child: push usage stats to Firestore
  Future<void> updateUsageStats(String deviceId, Map<String, dynamic> stats) async {
    try {
      final dateKey = DateTime.now().toString().substring(0, 10); // YYYY-MM-DD
      await _db.collection('devices').doc(deviceId).set({
        'usageStats': {
          dateKey: stats,
        }
      }, SetOptions(merge: true));
    } catch (e) {
      debugPrint('//TEST: updateUsageStats error: $e');
    }
  }

  /// Remove a device completely from Firestore
  Future<void> removeDevice(String deviceId) async {
    try {
      await _db.collection('devices').doc(deviceId).delete();
      debugPrint('//TEST: Device $deviceId removed successfully');
    } catch (e) {
      debugPrint('//TEST: Failed to remove device: $e');
      rethrow;
    }
  }

  /// Link child device to parent account
  Future<void> linkDeviceToParent({
    required String deviceId,
    required String parentUid,
  }) async {
    try {
      await _db.collection('devices').doc(deviceId).set({
        'parentUid': parentUid,
        'pairedAt': FieldValue.serverTimestamp(),
      }, SetOptions(merge: true));
      debugPrint('//TEST: Device linked: $deviceId to parent $parentUid');
    } catch (e) {
      debugPrint('//TEST: linkDeviceToParent error: $e');
      rethrow;
    }
  }

  /// Parent: save lock schedules list for a device
  Future<void> saveLockSchedules(
      String deviceId, List<Map<String, dynamic>> schedules) async {
    try {
      await _db.collection('devices').doc(deviceId).update({
        'lockSchedules': schedules,
      });
      debugPrint(
          '//TEST: saveLockSchedules: $deviceId count=${schedules.length}');
    } catch (e) {
      debugPrint('//TEST: saveLockSchedules error: $e');
      rethrow;
    }
  }

  // ─── FCM ─────────────────────────────────────────────────────────────────

  /// Request notification permissions + get FCM token
  Future<String?> initFCM({required String deviceId}) async {
    try {
      final settings = await _fcm.requestPermission(
        alert: true,
        badge: true,
        sound: true,
      );
      debugPrint('//TEST: FCM permission: ${settings.authorizationStatus}');

      final token = await _fcm.getToken();
      debugPrint('//TEST: FCM token: $token');

      if (token != null && deviceId.isNotEmpty) {
        // Store FCM token in device doc for parent to send messages
        await _db.collection('devices').doc(deviceId).update({
          'fcmToken': token,
        });
      }

      // Token refresh
      _fcm.onTokenRefresh.listen((newToken) async {
        debugPrint('//TEST: FCM token refreshed');
        if (deviceId.isNotEmpty) {
          await _db.collection('devices').doc(deviceId).update({
            'fcmToken': newToken,
          });
        }
      });

      return token;
    } catch (e) {
      debugPrint('//TEST: initFCM error: $e');
      return null;
    }
  }

  /// Send FCM command from parent to child device
  /// Commands: 'show_overlay', 'hide_overlay', 'force_unlock'
  /// Uses Firestore as the command relay (no server-side FCM needed)
  Future<void> sendCommand({
    required String deviceId,
    required String command, // 'show_overlay' | 'hide_overlay' | 'force_unlock'
  }) async {
    try {
      await _db.collection('devices').doc(deviceId).update({
        'pendingCommand': command,
        'commandTimestamp': FieldValue.serverTimestamp(),
      });

      // Also update locked state
      if (command == 'show_overlay') {
        await setDeviceLocked(deviceId, true);
      } else if (command == 'hide_overlay' || command == 'force_unlock') {
        await setDeviceLocked(deviceId, false);
      }

      debugPrint('//TEST: Command sent: $command to $deviceId');
    } catch (e) {
      debugPrint('//TEST: sendCommand error: $e');
      rethrow;
    }
  }

  /// Clear a pending command after it's been processed
  Future<void> clearPendingCommand(String deviceId) async {
    try {
      await _db.collection('devices').doc(deviceId).update({
        'pendingCommand': FieldValue.delete(),
        'commandTimestamp': FieldValue.delete(),
      });
    } catch (e) {
      debugPrint('//TEST: clearPendingCommand error: $e');
    }
  }

  /// Update device online/offline status and battery
  Future<void> updateDeviceStatus({
    required String deviceId,
    required String status,
    required int battery,
    double? lat,
    double? lng,
  }) async {
    try {
      final updates = {
        'status': status,
        'battery': battery,
        'lastSeen': FieldValue.serverTimestamp(),
      };
      if (lat != null) updates['lat'] = lat;
      if (lng != null) updates['lng'] = lng;

      await _db.collection('devices').doc(deviceId).update(updates);
    } catch (e) {
      debugPrint('//TEST: updateDeviceStatus error: $e');
    }
  }

  /// Update just the heartbeat (lastSeen)
  Future<void> updateHeartbeat(String deviceId) async {
    try {
      await _db.collection('devices').doc(deviceId).update({
        'lastSeen': FieldValue.serverTimestamp(),
      });
    } catch (e) {
      // Background failure expected if offline
    }
  }

  /// Update device control mode (Basic vs Advanced)
  Future<void> updateDeviceControlMode(String deviceId, String mode) async {
    try {
      await _db.collection('devices').doc(deviceId).update({'controlMode': mode});
      debugPrint('//TEST: Device $deviceId mode updated to $mode');
    } catch (e) {
      debugPrint('//TEST: updateDeviceControlMode error: $e');
    }
  }

  // ─── Chat Messages ────────────────────────────────────────────────────────

  /// Send a chat message in the device's messages subcollection.
  /// [sender] should be 'child' or 'parent'.
  Future<void> sendChatMessage(String deviceId, String text, String sender) async {
    try {
      await _db
          .collection('devices')
          .doc(deviceId)
          .collection('messages')
          .add({
        'text': text,
        'sender': sender,
        'timestamp': FieldValue.serverTimestamp(),
        'read': false,
      });
    } catch (e) {
      debugPrint('//TEST: sendChatMessage error: $e');
      rethrow;
    }
  }

  /// Stream all chat messages for a device, ordered by time.
  Stream<QuerySnapshot> streamChatMessages(String deviceId) {
    return _db
        .collection('devices')
        .doc(deviceId)
        .collection('messages')
        .orderBy('timestamp', descending: false)
        .snapshots();
  }

  /// Mark all messages from [otherSender] as read.
  Future<void> markMessagesRead(String deviceId, String otherSender) async {
    try {
      final unread = await _db
          .collection('devices')
          .doc(deviceId)
          .collection('messages')
          .where('sender', isEqualTo: otherSender)
          .where('read', isEqualTo: false)
          .get();
      final batch = _db.batch();
      for (final doc in unread.docs) {
        batch.update(doc.reference, {'read': true});
      }
      await batch.commit();
    } catch (e) {
      debugPrint('//TEST: markMessagesRead error: $e');
    }
  }
}
